version: "3.10"

services:
  app:
    build: .
    command: sh ./docker-entrypoint.sh
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/.env_surcoApp

  db:
    image: mysql
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .envs/.env_mysql
